site_name: 'ValidatedNumerics.jl'

site_description: 'ValidatedNumerics.jl: A Julia package for rigorous numerics'

repo_url: https://github.com/dpsanders/ValidatedNumerics.jl

pages:
    - 'Validated Numerics package': 'index.md'
    - 'Basic usage': 'usage.md'
    - 'Root finding': 'root_finding.md'
    - 'Rounding': 'rounding.md'

#theme: readthedocs

#markdown_extensions: [math]

copyright: Copyright &copy; 2014, 2015, Luis Benet & David P. Sanders
